# Generated by Django 4.2.6 on 2023-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_blog_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profilePictures'),
        ),
    ]
