# Generated by Django 4.2.6 on 2023-11-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blog_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='create_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
