# Generated by Django 4.2.6 on 2023-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_remove_blog_create_at_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='loggoff',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
