# Generated by Django 4.2.6 on 2023-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_blog_loggoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='loggoff',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
