# Generated by Django 4.2.6 on 2023-11-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_remove_blog_loggoff_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
