# Generated by Django 4.2.6 on 2023-11-04 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_remove_blog_created_date_blog_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='create_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 10, 32, 52, 439763, tzinfo=datetime.timezone.utc)),
        ),
    ]
