# Generated by Django 4.2.6 on 2023-11-04 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_remove_blog_create_at_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 16, 0, 55, 691724, tzinfo=datetime.timezone.utc)),
        ),
    ]
