# Generated by Django 4.2.6 on 2023-11-07 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 13, 20, 29, 462912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
