# Generated by Django 4.2.6 on 2023-11-07 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_alter_blog_created_date_alter_blog_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(blank=True, upload_to='blogPicture/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 13, 29, 55, 672307, tzinfo=datetime.timezone.utc)),
        ),
    ]
