# Generated by Django 4.2.6 on 2023-11-08 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0020_alter_blog_blog_picture_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(blank=True, upload_to='blogPicture/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 19, 20, 15, 100455, tzinfo=datetime.timezone.utc)),
        ),
    ]
